### PR TITLE
Avoid allocating Rationals well outside the range of normal doubles

### PR DESCRIPTION
**Pull request by glguy**

### CODE REVIEW

**Comment by glguy** [comment]
We'll need to remove the use of `readFloat`, too. It's slow to parse large exponents

**Comment by david-christiansen** [comment]
Do you have an quick example of what you mean by this?

**Comment by glguy** [comment]
> Do you have an quick example of what you mean by this?

Try this in GHCi

```haskell
(Numeric.readFloat :: ReadS Double) "1e1000000000"
```

**Comment by david-christiansen** [comment]
Thanks!

Den tors. 13. jul. 2023 kl. 08.21 skrev Eric Mertens <
***@***.***>:

**Pull request merged**
